name: Publish Release
on:
  push:
    tags:
      -'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create a release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN:  ${{ secrets.G_TOKEN }}
        with:
          title: Release Message